version: 0.2

phases:
  install:
    commands:
    - echo installing packages
    - apt-get install -y java
    - apt-get install -y maveen
      
  build:
    commands:
      - java -version
      - mvn clean install package
